#include "demo_host.h"
#include "YMGRE_Rendering_Pipeline.h"
#include "YMGRE_Camera.h"
#include "YMGRE_Creat.h"
#include "YMGRE_Free.h"
#include "YMGRE_List.h"
#include <stdio.h>
static GRE_Object4d createQuad(void){GRE_Object4d o=YMGRE_Creat_Object(3,1,"perspective_verify","checker");o->pointList[0]=(gre_vertex4d){{-120,-95,90,1},0,1};o->pointList[1]=(gre_vertex4d){{125,-80,300,1},1,1};o->pointList[2]=(gre_vertex4d){{0,130,170,1},.5f,0};o->polygonList[0].num=3;o->polygonList[0].index=GRE_PolyIndex_Malloc(3*sizeof(uint16));o->polygonList[0].index[0]=0;o->polygonList[0].index[1]=2;o->polygonList[0].index[2]=1;o->polygonList[0].pN=(gre_fvector4d){0,0,-1,0};o->polygonList[0].planeColor=(GRErgb24){255,255,255};o->BoundingSphereR=240;o->boundType=GRE_Bounding_Sphere_R;YMGRE_Object_GenerateVertexAttributes(o);o->renderMode=GRE_RenderMode_Pixel;return o;}
static GRE_Material createChecker(void){GRE_Material m=YMGRE_Creat_Material("checker");m->width=m->height=32;m->pixel=GRE_ImageBuff_Malloc(1024*sizeof(GRErgb24));for(int y=0;y<32;y++)for(int x=0;x<32;x++)m->pixel[y*32+x]=(GRErgb24){(uint8)(x*8),(uint8)(y*8),(uint8)(255-x*4)};return m;}
static void printSample(float32 a,float32 b,float32 c){float32 iw0=a/90,iw1=b/300,iw2=c/170;float32 affine=b+c*.5f;float32 perspective=(iw1+iw2*.5f)/(iw0+iw1+iw2);printf("barycentric=(%.2f, %.2f, %.2f): affine U=%.6f, perspective U=%.6f, delta=%.6f\n",a,b,c,affine,perspective,perspective-affine);}
static void verifyFramebuffer(GRE_Camera4d c,GRE_Object4d o,GRE_Material m){gre_fvector4d p[3];int ids[3]={0,2,1};for(int i=0;i<3;i++){YMGRE_Point_WorldToCamera(&o->pointList[ids[i]].pos,&p[i],&c->move.TMat);YMGRE_Point_CameraToViewPlane(&p[i],c->perspectPlane.Dis);YMGRE_Point_ViewPlaneToWindows(&p[i],c);}int x=(int)(.25f*p[0].x+.50f*p[1].x+.25f*p[2].x);int y=(int)(.25f*p[0].y+.50f*p[1].y+.25f*p[2].y);float32 den=(p[1].y-p[2].y)*(p[0].x-p[2].x)+(p[2].x-p[1].x)*(p[0].y-p[2].y);float32 a=((p[1].y-p[2].y)*(x-p[2].x)+(p[2].x-p[1].x)*(y-p[2].y))/den;float32 b=((p[2].y-p[0].y)*(x-p[2].x)+(p[0].x-p[2].x)*(y-p[2].y))/den;float32 d=1-a-b;float32 iz=a/90+b/170+d/300;float32 u=(b*.5f/170+d/300)/iz;float32 v=(a/90+d/300)/iz;int tx=(int)(u*32+1e-5f),ty=(int)(v*32+1e-5f);if(tx>31)tx=31;if(ty>31)ty=31;GRE_FramePixel expected=GRE_FramePixel_From_RGB24(m->pixel[ty*32+tx]);GRE_FramePixel actual=c->img.data[y*c->img.width+x];printf("framebuffer sample=(%d,%d), perspective UV=(%.6f,%.6f), texel=(%d,%d): %s\n",x,y,u,v,tx,ty,GRE_FramePixel_Equals(actual,expected)?"PASS":"FAIL");}
int main(void){printSample(.25f,.50f,.25f);printSample(.20f,.30f,.50f);gre_list o={0},l={0},m={0};GRE_Object4d object=createQuad();GRE_Material material=createChecker();YMGRE_List_Append(&o,sizeof(gre_object4d),object);YMGRE_List_Append(&m,sizeof(gre_material),material);YMGRE_List_Append(&l,sizeof(gre_light4d),YMGRE_Creat_Light(0,GRE_GlobalLight,(GRErgb24){255,255,255},1));GRE_Camera4d c=YMGRE_Creat_Camera(0,720,440,42,42,38,38);YMGRE_Camera_Frustum_Init(c,1,500);gre_fvector4d e={0,0,0,1},t={0,0,180,1};YMGRE_UVNCamera_PositionInit(c,&e,&t,NULL,0);GRE_RenderWorkspace w=YMGRE_Creat_RenderWorkspace();YMGRE_Camera_TanglePipline_wN(c,&l,&o,&m,w);verifyFramebuffer(c,object,material);GRE_RenderTarget out=YMGRE_Camera_GetRenderTarget(c);YMGRE_DemoView v={out,0,0,out->width,out->height};YMGRE_DemoHost_Show(out->width,out->height,&v,1,60);YMGRE_Free_RenderWorkspace(w);YMGRE_Free_Camera(c);YMGRE_List_Clear(&l,YMGRE_Free_Light);YMGRE_List_Clear(&o,YMGRE_Free_Object);YMGRE_List_Clear(&m,YMGRE_Free_Material);return 0;}
