#!/usr/bin/env python3
"""Build the two native RGB565 archives and a relocatable, source-free SDK."""
import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import tarfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'build/YMGRE_libs'
WORK = ROOT / 'build/_ymgre_sdk'
DEMOS = '''basic_shapes extended_shapes polygon_fill polygon_triangulation depth_overlap
frustum_clipping window_clipping backface_culling fragment_stitching shared_edge_stress
material_texture lighting render_target camera_viewport stereo_view
advanced_vertex advanced_texture advanced_perspective advanced_normal_map
advanced_specular advanced_render_modes advanced_clipping_planes
advanced_raytrace advanced_raytrace_object advanced_raytrace_shading
advanced_raytrace_shadow advanced_raytrace_mirror advanced_raytrace_refraction
advanced_raytrace_materials'''.split()

def run(args, log, cwd=ROOT, env=None):
    print(' '.join(map(str, args)), flush=True)
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open('w') as stream:
        subprocess.run(list(map(str,args)), cwd=cwd, env=env, stdout=stream,
                       stderr=subprocess.STDOUT, check=True)

def copy(source, dest):
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dest)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ymgui-dir',type=Path,help='Optional external YMGUI CMake package; validates window examples without bundling YMGUI')
    args=parser.parse_args()
    for command in ('cmake','cc','ar','nm'):
        if not shutil.which(command):raise SystemExit(f'Missing build dependency: {command}')
    if OUT.exists() and any(OUT.iterdir()) and not (OUT/'.ymgre-sdk').exists():
        raise SystemExit(f'Refusing to overwrite an unmanaged directory: {OUT}')
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT/'.ymgre-sdk').write_text('Generated by sdk/package.py\n')
    # Remove obsolete generated dependencies and window binaries from older SDKs.
    for relative in ('support','include/YMGUI','include/SDL_LCD','include/demo_host.h',
                     'licenses/YMGUI-LICENSE','bin','verification'):
        old=OUT/relative
        if old.is_dir():shutil.rmtree(old)
        elif old.exists():old.unlink()
    for bits in (16,32):
        build=WORK/f'index{bits}'
        run(['cmake','-S',ROOT/'sdk/library','-B',build,
             '-DCMAKE_BUILD_TYPE=Release',f'-DYMGRE_INDEX_BITS={bits}'], WORK/f'configure{bits}.log')
        run(['cmake','--build',build,'--target','ymgre','-j4'], WORK/f'build{bits}.log')
        copy(build/'engine/libymgre.a', OUT/f'lib/libymgre_index{bits}.a')
    for section in ('CONFIG','CORE','OPOBJ','IOFILE','DEBUG'):
        for header in (ROOT/'YMGRE'/section).glob('*.h'):
            copy(header,OUT/'include/YMGRE'/section/header.name)
    for name in ('demo_host.c','demo_host.h'):
        copy(ROOT/'Demo'/name,OUT/'examples/host'/name)
    copy(ROOT/'sdk/YMGREConfig.cmake',OUT/'cmake/YMGREConfig.cmake')
    for item in (ROOT/'sdk/examples').iterdir():
        if item.is_file():copy(item,OUT/'examples'/item.name)
    for name in DEMOS:copy(ROOT/f'Demo/demo_{name}.c',OUT/f'examples/demo_{name}.c')
    copy(ROOT/'sdk/MANUAL.md',OUT/'手册.md')
    copy(ROOT/'sdk/SDK.gitignore',OUT/'.gitignore')
    copy(ROOT/'sdk/build_demos.sh',OUT/'build_demos.sh')
    copy(ROOT/'LICENSE',OUT/'licenses/YMGRE-LICENSE')
    copy(ROOT/'sdk/README.md',OUT/'README.md')
    for name in ('advanced_raytrace_mirror','advanced_raytrace_refraction','advanced_perspective','advanced_normal_map'):
        copy(ROOT/'docs/images'/f'{name}.png',OUT/'docs/images'/f'{name}.png')
    # Validate from a separate package copy: this must not resolve repository source paths.
    standalone=WORK/'standalone'
    if standalone.exists():shutil.rmtree(standalone)
    shutil.copytree(OUT,standalone,ignore=shutil.ignore_patterns('bin','verification','checksums.sha256'))
    for bits in (16,32):
        consumer=WORK/f'consumer{bits}'
        run(['cmake','-S',standalone/'examples','-B',consumer,f'-DYMGRE_INDEX_BITS={bits}',
             '-DCMAKE_BUILD_TYPE=Release','-DYMGRE_WINDOWED_DEMOS=OFF'],WORK/f'consumer-configure{bits}.log')
        run(['cmake','--build',consumer,'-j4'],WORK/f'consumer-build{bits}.log')
        run(['ctest','--test-dir',consumer,'--output-on-failure'],OUT/f'verification/demos-index{bits}.log')
        for binary in (consumer/'bin').iterdir():
            if binary.name=='demo_sdk_minimal':copy(binary,OUT/f'bin/index{bits}'/binary.name)
    if args.ymgui_dir:
        for bits in (16,32):
            consumer=WORK/f'external-gui{bits}'
            run(['cmake','-S',standalone/'examples','-B',consumer,f'-DYMGRE_INDEX_BITS={bits}',
                 '-DYMGRE_WINDOWED_DEMOS=ON',f'-DYMGUI_DIR={args.ymgui_dir.resolve()}',
                 '-DCMAKE_BUILD_TYPE=Release'],WORK/f'gui-configure{bits}.log')
            run(['cmake','--build',consumer,'-j4'],WORK/f'gui-build{bits}.log')
            run(['ctest','--test-dir',consumer,'--output-on-failure'],OUT/f'verification/external-gui-index{bits}.log')
    # Core archives must not reference GUI/SDL symbols, even indirectly.
    for bits in (16,32):
        symbols=subprocess.check_output(['nm','-u',str(OUT/f'lib/libymgre_index{bits}.a')],text=True)
        if any(name in symbols for name in ('YMGUI_','SDL_','SDL_LCD_')):
            raise SystemExit('Unexpected GUI dependency in core archive')
    sources=sorted(p for folder in ('YMGRE','Demo','sdk') for p in (ROOT/folder).rglob('*')
                   if p.is_file() and p.suffix in ('.c','.h','.py','.cmake','.md','.txt'))
    digest=hashlib.sha256()
    for p in sources:
        digest.update(str(p.relative_to(ROOT)).encode());digest.update(p.read_bytes())
    info={'built_at_utc':datetime.now(timezone.utc).isoformat(),'system':platform.system(),
          'machine':platform.machine(),'compiler':subprocess.check_output(['cc','--version'],text=True).splitlines()[0],
          'build_type':'Release','position_independent':True,'framebuffer':'RGB565',
          'index_bits':[16,32],'example_sources':len(DEMOS)+1,'prebuilt_demos_per_variant':1,
          'external_ymgui_validated':bool(args.ymgui_dir),'bundled_ymgui':False,'source_sha256':digest.hexdigest(),
          'git_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
          'source_includes_uncommitted_changes':True,
          'sdk_requires_engine_source':False,'rebuild_command':'./sdk/build.sh'}
    (OUT/'BUILD_INFO.json').write_text(json.dumps(info,ensure_ascii=False,indent=2)+'\n')
    (OUT/'checksums.sha256').write_text(''.join(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+str(p.relative_to(OUT))+'\n'
        for p in sorted(OUT.rglob('*')) if p.is_file() and p.name!='checksums.sha256'))
    archive=OUT.parent/f'YMGRE_libs-{platform.system().lower()}-{platform.machine()}.tar.gz'
    with tarfile.open(archive,'w:gz') as bundle:
        bundle.add(OUT,arcname='YMGRE_libs')
    checksum=hashlib.sha256(archive.read_bytes()).hexdigest()
    archive.with_name(archive.name+'.sha256').write_text(checksum+'  '+archive.name+'\n')
    print(f'SDK complete: {OUT}\nArchive: {archive}\nSHA256: {checksum}',flush=True)

if __name__=='__main__':main()
